---
title: "MUAC Data quality and plausibility Report"
subtitle: "`r Sys.Date()`"
output: html_document
params:
  mainData: NULL
  uuidVar: "uuid"
  YesNoTeam: "no"
  TeamVar: "team"
  GroupVar: "enum_id"
---

<style>
.tocify-subheader {
  font-size: 0.7em;
}
.tocify-item {
  font-size: 0.85em;
  padding-left: 25px;
  text-indent: 0;
}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
options(scipen = 999)
```

```{r, include=FALSE, eval=TRUE}

# raw.main <- params$mainData

raw.main <- impactR4PHU::impactR4PHU_data_nut_template

library(tidyverse)
library(devtools)

```

# {.tabset .tabset-fade}

## Introduction

```{r, results='asis'}
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is this tool?"))
  cat('\nThe MUAC Data Quality and Plausibility Report serves as a crucial tool for assessing the reliability and accuracy of the data collection of MUAC indicators across different assessments. This comprehensive analysis is designed to identify and address potential issues within the data, ensuring that field teams are being informed on potential issues detected in the data collection.\n\nThe report provides a detailed examination of the datasets, employing a variety of metrics and methodologies to evaluate data quality and plausibility. This includes checks for completeness, consistency, and accuracy of the data collected. This report aims to uncover any discrepancies, outliers, or anomalies that may suggest data collection, entry errors, or underlying issues that could impact the integrity of the findings.</p>')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is in this tool?")) 
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "FSL SECTION"))
  cat('\nThis section includes:\n\n- Overall Plausibility Report / By Enumerator\n- All the flags related to Food Security and Livelihoods (details shown for each flag in the section)\n- Plots showing the distribution of the data.')

  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What to do next?"))
  cat('\nPlease check each flag and the <strong>ACTION</strong> related to it and act accordingly.\n\nAnother output will be associated to this HTML, the Excel file of the flags that were fired and requires follow-up with the field team. Please check the README tab in the excel file. This file will again be generated with the full data during the cleaning of the dataset. So please do use this file during data collection and relate to it in the final one to be filled.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "Feedback"))
  cat('\nFeedback on improvements to this product can be done through reaching out to:\n\n-saeed.rahman@impact-initiatives.org \n\n-impact.geneva.phu@impact-initiatives.org')
```

## MUAC {.tabset .tabset-fade}

```{r, echo=FALSE, warning=FALSE,include=FALSE}

  uuid_main <- params$uuidVar

  ## Set Team column

    yes_no_team <- params$YesNoTeam
 
    team <- params$TeamVar
  
  ## Set Enumerator column
  enumerator <- params$GroupVar
  
    #   fcs_check_columns <- c("fsl_fcs_cereal",
    #                        "fsl_fcs_legumes",
    #                        "fsl_fcs_veg",
    #                        "fsl_fcs_fruit",
    #                        "fsl_fcs_meat",
    #                        "fsl_fcs_dairy",
    #                        "fsl_fcs_sugar",
    #                        "fsl_fcs_oil")
    #   
    #   rcsi_check_columns <- c("fsl_rcsi_lessquality",
    #                         "fsl_rcsi_borrow",
    #                         "fsl_rcsi_mealsize",
    #                         "fsl_rcsi_mealadult",
    #                         "fsl_rcsi_mealnb")
    # 
    #   hhs_check_columns <- c("fsl_hhs_nofoodhh",
    #                        "fsl_hhs_sleephungry",
    #                        "fsl_hhs_alldaynight")
    # 
    # hhs_check_columns_freq <- c("fsl_hhs_nofoodhh_freq",
    #                             "fsl_hhs_sleephungry_freq",
    #                             "fsl_hhs_alldaynight_freq")
      
## FCS
raw.flag.muac <- impactR4PHU::impactR4PHU_data_nut_template %>%
  impactR4PHU::add_muac(nut_muac_cm = "nut_muac_cm", child_age_months = "child_age_months", child_sex = "child_sex",
                        value_male_sex = "m", edema_confirm = "nut_edema_confirm", value_edema_confirm = "yes") %>%
  impactR4PHU::add_mfaz(nut_muac_cm = "nut_muac_cm", child_age_months = "child_age_months", child_sex = "child_sex",
                        value_male_sex = "m", edema_confirm = "nut_edema_confirm", value_edema_confirm = "yes") %>%
  impactR4PHU::check_anthro_flags(nut_muac_cm = "nut_muac_cm",edema_confirm = "nut_edema_confirm", value_edema_confirm = "yes",
                                  uuid = "child_person_id") %>% 
  dplyr::mutate(enum_id = sample(1:2, size = nrow(.), replace = TRUE))

# list_of_var <- c("uuid_main","FSL_indicators","num_children","income_types", "fsl_fcs_cereal","fsl_fcs_legumes",
#                  "fsl_fcs_veg","fsl_fcs_fruit","fsl_fcs_meat","fsl_fcs_dairy","fsl_fcs_sugar",
#                  "fsl_fcs_oil","fsl_rcsi_lessquality","fsl_rcsi_borrow","fsl_rcsi_mealsize","fsl_rcsi_mealadult",
#                  "fsl_rcsi_mealnb","fsl_hhs_nofoodhh","fsl_hhs_nofoodhh_freq","fsl_hhs_sleephungry","fsl_hhs_sleephungry_freq",
#                  "fsl_hhs_alldaynight","fsl_hhs_alldaynight_freq","yes_answer","no_answer","rarely_answer","sometimes_answer","often_answer",
#                  "fsl_lcsi_stress1","fsl_lcsi_stress2","fsl_lcsi_stress3","fsl_lcsi_stress4","yes_val_hdds","no_val_hdds",
#                  "fsl_lcsi_crisis1","fsl_lcsi_crisis2","fsl_lcsi_crisis3","fsl_lcsi_emergency1",
#                  "fsl_lcsi_emergency2","fsl_lcsi_emergency3","yes_val","no_val","exhausted_val","not_applicable_val",
#                  "fsl_hdds_cereals","fsl_hdds_tubers","fsl_hdds_veg","fsl_hdds_fruit","fsl_hdds_meat",
#                  "fsl_hdds_eggs","fsl_hdds_fish","fsl_hdds_legumes","fsl_hdds_dairy","fsl_hdds_oil","fsl_hdds_sugar","fsl_hdds_condiments",
#                  "fclcm_check_columns","fcm_check_1_columns","fcm_check_2_columns","fcm_check_3_columns",
#                  "fcm_check_4_columns","fcm_check_5_columns","fcm_check_6_columns","hhs_check_columns_freq",
#                  "residency_status","value_idp","team","yes_no_team",
#                  "hdds_check_columns","lcsi_check_columns","hhs_check_columns","rcsi_check_columns","fcs_check_columns", "enumerator")

# if(!file.exists("inputs/environment.Rdata")){
#   save(list = list_of_var, file = "inputs/environment.Rdata")
# }
```

```{r, include = FALSE}
## Read the Plausibility excel file
overall_muac_plaus <- openxlsx::read.xlsx(xlsxFile = "resources/overall_plaus.xlsx", fillMergedCells = TRUE, sheet = "NUT") %>%
  dplyr::distinct()

result <- impactR4PHU::create_muac_plaus(raw.flag.muac) %>%
  impactR4PHU::calculate_plausibility()

result_muac_enum <- impactR4PHU::create_muac_plaus(raw.flag.muac,
                                        grouping = enumerator)  %>%
  impactR4PHU::calculate_plausibility()

result_pivot <- result %>%
  dplyr::mutate_all(., as.character) %>%
  tidyr::pivot_longer(cols = everything(),names_to = "Criteria",
               values_to = "Score") %>%
  dplyr::filter(stringr::str_starts(string = Criteria, "plaus_")) %>%
  dplyr::filter(Criteria != "plaus_hhs" & Criteria != "plaus_fsl_score" & Criteria != "plaus_fsl_cat")

# bind <- data.frame(`Indicator Score` = c("plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs",
#                                          "plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs","plaus_fcs",
#                                          "plaus_rcsi","plaus_rcsi","plaus_rcsi","plaus_rcsi","plaus_rcsi",
#                                          "plaus_rcsi","plaus_rcsi","plaus_rcsi","plaus_rcsi","plaus_rcsi",
#                                          "plaus_hhs","plaus_hhs",
#                                          "plaus_lcsi","plaus_lcsi","plaus_lcsi","plaus_lcsi","plaus_lcsi",
#                                          "plaus_lcsi","plaus_lcsi","plaus_lcsi","plaus_lcsi","plaus_lcsi",
#                                          "plaus_other_fsl","plaus_other_fsl","plaus_other_fsl",
#                                          "plaus_other_fsl","plaus_other_fsl","plaus_other_fsl",
#                                          "plaus_other_fsl","plaus_other_fsl","plaus_other_fsl",
#                                          "plaus_other_fsl","plaus_other_fsl","plaus_other_fsl",NA,NA))

overall_muac_plaus_overall <- overall_muac_plaus %>%
  dplyr::left_join(result_pivot, by = c("flag_name"="Criteria")) %>%
  dplyr::mutate_all(., ~ifelse(is.na(.),"NA",.)) 
# %>%
  # # cbind(bind)%>%
  # # dplyr::left_join(result_pivot %>% filter(Criteria %in% c("plaus_other_fsl",
  # #                                                   "plaus_lcsi",
  # #                                                   "plaus_hhs",
  # #                                                   "plaus_rcsi",
  # #                                                   "plaus_fcs")) %>%
  #             rename(indscore = "Score"), by = c("Indicator.Score"="Criteria")) %>%
  # dplyr::mutate(indscore = case_when(flag_name == "plaus_flag_severe_hhs"~paste0(indscore,"/10"),
  #                             TRUE ~paste0(indscore,"/20"))) %>%
  # dplyr::select(-Indicator.Score)

muac <- flextable::flextable(overall_muac_plaus_overall)


final_table <- impactR4PHU::create_table_nut(muac)

```

### Data Quality MUAC {.tabset .tabset-fade}

#### Plausibility {.tabset .tabset-fade}

##### Overall

```{r}

final_table

```

```{r, results='asis'}
result_muac_pivot <- result_muac_enum %>%
  dplyr::mutate_all(., as.character) %>%
  tidyr::pivot_longer(-enumerator,names_to = "Criteria",
               values_to = "Score") %>%
  dplyr::filter(stringr::str_starts(string = Criteria, "plaus_")) %>%
  dplyr::filter(Criteria != "plaus_hhs" & Criteria != "plaus_fsl_score" & Criteria != "plaus_fsl_cat")

  list_enum <- result_muac_pivot[enumerator] %>% unique
  
  for (i in 1:length(list_enum)) {
    cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",5), collapse=""), " ", "<strong>",i,"</strong>"))
    
    overall_muac_plaus_enum <- overall_muac_plaus %>%
      dplyr::left_join(result_muac_pivot %>% dplyr::filter(!!rlang::sym(enumerator) == as.numeric(list_enum[[i]])), by = c("flag_name"="Criteria"))%>%
      dplyr::mutate_all(., ~ifelse(is.na(.),"NA",.)) %>%
      dplyr::select(-!!rlang::sym(enumerator))

    muac_enum <- flextable::flextable(overall_muac_plaus_enum)
  
    final_table_muac_enum <- impactR4PHU::create_table_nut(muac_enum)
    subch(final_table_muac_enum)
  }




```


```{r, results='asis'}
flag_description <- readxl::read_excel("resources/flag_description.xlsx", sheet = "NUT")
flags_muac_columns <- names(raw.flag.muac)[stringr::str_starts(names(raw.flag.muac),"flag_")]

overall_flag <- tibble::tibble()

for(i in 1:length(flags_muac_columns)) {
  
  flag <- flags_muac_columns[[i]]
  
  flag_overall <- raw.flag.muac %>%
    dplyr::select(enumerator, !!rlang::sym(flag)) %>%
    filter(!is.na(!!rlang::sym(flag))) %>%
    dplyr::mutate(flag := flag) %>%
    dplyr::group_by(flag) %>%
    dplyr::summarise(num_samples = n(),
              flagged = sum(!!rlang::sym(flag))) %>%
    dplyr::mutate(percentage_flaggged = paste0(round((flagged/num_samples)*100,2),"%")) %>%
    dplyr::ungroup()
  if(nrow(flag_overall)>0){
    overall_flag <- rbind(overall_flag,flag_overall)
  }
  
  
  # flag <- flags_muac_columns[[i]]
  # 
  # flag_sym <- rlang::sym(flags_muac_columns[[i]])
  # 
  # print(flag)
  # print(class(flag))
  # 
  # flag_overall <- raw.flag.muac %>%
  #   dplyr::select(enumerator, flag) %>%
  #   dplyr::mutate(flag := flag)
  
  
  # flag_overall <- raw.flag.muac %>%
  #   dplyr::select(enumerator, flag) %>%
  #   filter(!is.na(!!flag_sym)) %>%
  #   dplyr::mutate(flag := flag_sym) %>%
  #   dplyr::group_by(flag_sym) %>%
  #   dplyr::summarise(num_samples = n(),
  #             flagged = sum(!!flag_sym)) %>%
  #   dplyr::mutate(percentage_flaggged = paste0(round((flagged/num_samples)*100,2),"%")) %>%
  #   dplyr::ungroup()
  # 
  
  # if(nrow(flag_overall)>0){
  #   overall_flag <- rbind(overall_flag,flag_overall)
  # }
}



add_to_html.title("Overall Flag Table")
subch(DT::datatable(overall_flag,
                  extensions = 'Buttons', options = list(
                    dom = 'Blfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf'),
                    lengthMenu = list(c(50),
                                      c('All')),
                    paging = T)))

for(i in 1:length(flags_muac_columns)) {
  
  flag <- flags_muac_columns[[i]]
  
  flag_rational <- flag_description %>%
    filter(flag_name %in% flag) %>%
    dplyr::pull(Rationale)
  flag_action <- flag_description %>%
    filter(flag_name %in% flag) %>%
    dplyr::pull(Action)
  flag_by_enum <- raw.flag.muac %>%
    dplyr::select(enumerator, !!rlang::sym(flag)) %>%
    filter(!is.na(!!rlang::sym(flag))) %>%
    dplyr::mutate(flag := flag) %>%
    dplyr::group_by(flag,!!rlang::sym(enumerator)) %>%
    dplyr::summarise(num_samples = n(),
              flagged = sum(!!rlang::sym(flag))) %>%
    dplyr::mutate(percentage_flagged = paste0(round((flagged/num_samples)*100,2),"%")) %>%
    dplyr::ungroup() %>%
    dplyr::select(-1)
  if(nrow(flag_by_enum)>0){
    add_to_html.title(flag)
    cat("\n")
    cat(paste("<em><strong>Rational</strong>: ",flag_rational,"</em>\n"))
    if(!is.null(flag_action)){
      cat("\n")
      cat(paste("<em><strong>Action</strong>: ",flag_action,"</em>\n"))
    }
    subch(DT::datatable(flag_by_enum,
                  extensions = 'Buttons', options = list(
                    dom = 'Blfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf'),
                    lengthMenu = list(c(50),
                                      c('All')),
                    paging = T)))
  }
}



```

### Plots {.tabset .tabset-fade}

#### Age in Months Distribution Plot

```{r, results='asis'}

  
  impactR4PHU::plot_age_distribution(.dataset = raw.flag.muac, age_months = "child_age_months", year_or_month = "month", breaks = 1, min_age = 0, max_age = 60, title_name = "Overall Age in Months Distribution")
  
  
  # impactR4PHU::plot_ridge_distribution(raw.flag.fcs, numeric_cols = c("fsl_fcs_cereal", "fsl_fcs_dairy", "fsl_fcs_veg", 
  #                                                                      "fsl_fcs_fruit", "fsl_fcs_legumes", "fsl_fcs_sugar", 
  #                                                                      "fsl_fcs_oil","fsl_fcs_meat"),
  #                                       name_groups = "Food Groups", name_units = "Days")
  
```

#### Age in Months by Team/Enumerator Distribution Plot {.tabset .tabset-fade}

```{r, results='asis'}

    (  impactR4PHU::plot_age_distribution(.dataset = raw.flag.muac, age_months = "child_age_months", year_or_month = "month", breaks = 1, min_age = 0, max_age = 60, title_name = "Age in Months Distribution", by_group = enumerator))
 
```
