---
title: "Mortality Data Cleaning and Follow up Report"
subtitle: "`r Sys.Date()`"
output: html_document
---

<style>
.tocify-subheader {
  font-size: 0.7em;
}
.tocify-item {
  font-size: 0.85em;
  padding-left: 25px;
  text-indent: 0;
}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
options(scipen = 999)
```

```{r logo, echo=FALSE}
htmltools::img(src = knitr::image_uri("resources/Logo_Reach_RGB_1.png"),
               alt = "REACH logo",
               style = 'position:absolute; top:0; right:0; padding:0; margin:20; width:250px')
```

```{r, include=FALSE, eval=TRUE}
if(file.exists("inputs/environment.Rdata")) {
  load("inputs/environment.Rdata")
}

path.raw <- svDialogs::dlg_open(multiple = F, title = "Please select your data excel file.")$res
path.tool <- svDialogs::dlg_open(multiple = F, title = "Please select your Kobo tool file.")$res
label_colname <- tcltk::tk_select.list(names(tool.survey)[grepl("label",names(tool.survey))], title = "Label column to choose", multiple = F)
tool.survey <- load.tool.survey(path.tool)
tool.choices <- load.tool.choices(path.tool)
main.sheets <- readxl::excel_sheets(path.raw)
if(!file.exists("inputs/environment.Rdata")){
  path.sheet.with.main <- tcltk::tk_select.list(main.sheets, title = "Main Sheet", multiple = F)
}

raw.main <- readxl::read_excel(path.raw, path.sheet.with.main)

```


# {.tabset .tabset-fade}

## Introduction

```{r, results='asis'}
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is this tool?"))
  cat('\nThe Mortality Data Cleaning Template serves as a crucial tool for assessing the data collection of mortality indicators across different assessments. This comprehensive tool is designed to identify and address potential issues within the data, ensuring that field teams are being followed up on potential issues detected in the data collection.\n\nThe report provides a detailed examination of the datasets, employing a variety of metrics and methodologies to evaluate data quality. This report aims to uncover any discrepancies, outliers, or anomalies that may suggest data collection, entry errors, or underlying issues that could impact the integrity of the findings.</p>')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What is in this tool?")) 
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Mortality SECTION"))
  cat('\nThis section includes two sections:\n\n- A first section covering all potential logical checks that can be directly cleaned. It will also produce a file called cleaning_logbook.xlsx in the output/ folder to use as cleaning log.\n- A second section covering all the other logical checks that requires follow up with the field team.')
  
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",4), collapse=""), " ", "Follow-up Checks"))
  cat('\n-Check 1: Respondent reported more than 2 death in the HH.')
  
  
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "What to do next?"))
  cat('\nPlease check the files in the output/ folder. The cleaning_logbook.xlsx already can contain some of the directly cleaned data. The Mort_followup_request.xlsm file represent the checks that needs to be followed up with the field team. Please follow the instruction in the READ_ME tab to know how to fill the file.\n\nAfter filling the file, you can merge the [uuid/variable/old.value/new.value/issue] from the filled file with the cleaning_logbook.xlsx and add them to your cleaning scripts.')
  cat(paste0(paste0(rep("\n",2), collapse=""), paste0(rep("#",3), collapse=""), " ", "Feedback"))
  cat('\nFeedback on improvements to this product can be done through reaching out to:\n\n-abraham.azar@impact-initiatives.org \n\n-impact.geneva.phu@impact-initiatives.org')

```

## Mortality 


```{r, echo=FALSE, warning=FALSE,include=FALSE}
if(!file.exists("inputs/environment.Rdata")) {
  
  ## Detect Enumerator column
  enumerator <- names(raw.main)[grepl("enum|team",names(raw.main))]
  
  if(length(enumerator) == 1){
    yes_no <- svDialogs::dlg_message(paste0("Is '", enumerator, "' the correct enumerator column?"), type = "yesno")$res
    if(yes_no == "no"){
      enumerator <- svDialogs::dlg_input(message= "Enter the name of the Enumerator Column","enumerator")$res
    }
  } else if (length(enumerator) > 1){
    enumerator <- tcltk::tk_select.list(enumerator, title = "Enumerator Column")
    if(enumerator == "") {
      enumerator <- svDialogs::dlg_input(message= "Enter the name of the Enumerator Column","enumerator")$res
    }
  } else if (length(enumerator) == 0) {
    enumerator <- svDialogs::dlg_input(message= "Enter the name of the Enumerator Column","enumerator")$res
  }
  
  
  ## Detect uuid_main column
  uuid_main <- names(raw.main)[grepl("uuid",names(raw.main))]
  
  if(length(uuid_main) == 1){
    yes_no <- svDialogs::dlg_message(paste0("Is '", uuid_main, "' the correct HH UUID column in main data?"), type = "yesno")$res
    if(yes_no == "no"){
      uuid_main <- svDialogs::dlg_input(message= "Enter the name of the HH UUID Column in main data","uuid_main")$res
    }
  } else if (length(uuid_main) > 1){
    uuid_main <- tcltk::tk_select.list(uuid_main, title = "HH UUID Column [Main Data]")
    if(uuid_main == "") {
      uuid_main <- svDialogs::dlg_input(message= "Enter the name of the HH UUID Column in main data","uuid_main")$res
    }
  } else if (length(uuid_main) == 0) {
    uuid_main <- svDialogs::dlg_input(message= "Enter the name of the HH UUID Column in main data","uuid_main")$res
  }
  
  
  
    ## Detect num_died column
    num_died <- names(raw.main)[grepl("death|num_died|dead",names(raw.main))]
  
   if(length(num_died) == 1){
    yes_no <- svDialogs::dlg_message(paste0("Is '", num_died, "' the correct number of Death column in main data?"), type = "yesno")$res
    if(yes_no == "no"){
      num_died <- svDialogs::dlg_input(message= "Enter the number of Death column in main data","num_died")$res
    }
  } else if (length(num_died) > 1){
    num_died <- tcltk::tk_select.list(num_died, title = "Number of Death Column [Main Data]")
    if(num_died == "") {
      num_died <- svDialogs::dlg_input(message= "Enter the number of Death column in main data","num_died")$res
    }
  } else if (length(num_died) == 0) {
    num_died <- svDialogs::dlg_input(message= "Enter the number of Death column in main data","num_died")$res
  }
}
  


raw.main <- raw.main %>% 
  dplyr::rename(enumerator = enumerator,
                num_died = num_died)


  
  list_of_var <- c("enumerator","uuid_main","label_colname","path.sheet.with.main",
                   "num_died")
  
  if(!file.exists("inputs/environment.Rdata")){
    save(list = list_of_var, file = "inputs/environment.Rdata")
  }
```


```{r, include = FALSE}
# FLAG Logical Checks
checks_followups <- tibble()

# Check number 1
if("num_died" %in% names(raw.main)){
  check_multiple_death <- raw.main %>%
    dplyr::select(uuid_main, enumerator, num_died) %>% 
    filter(num_died > 1) %>% 
    dplyr::rename(uuid = uuid_main)

  if(nrow(check_multiple_death)>0){
    checks_followups <- rbind(checks_followups,
                              make.logical.check.entry(check_multiple_death, 1,  "num_died",
                                                       cols_to_keep = c(enumerator),"Respondent reported more than 2 death in the HH", F))
  }
}


if(nrow(checks_followups) > 0){
  create.follow.up.requests(checks_followups,loop_data = NULL, paste0("Mort_followup_requests.xlsm"), use_template = T)
  options(warn=0)
  cat("\n\n#############################################################################################\n")
  cat("Logical checks are flagged and a file is created for follow up in \noutput/checking/requests/ with follow_up_requests in the title. \nPlease check the READ_ME file for information on filling the file.\n")
  cat("#############################################################################################\n")
} else {
  cat("\n\n#############################################################################################\n")
  cat(" No logical checks were flagged!!. All good with cleaning for Mortality")
  cat("#############################################################################################\n")
}
```

<h5>Number of detected entries with Respondent reported more than 2 death in the HH:<strong> `r if(nrow(checks_followups)>0) {nrow(checks_followups %>% filter(check.id == 1)%>% distinct(uuid) )}else {0}`</strong></h5>

```{r}
if(nrow(checks_followups)>0){
  cat("The below table shows the data that needs follow up with the field.")
  DT::datatable(checks_followups)
} else {
  cat("No Logical checks were detected in the dataset.")
}
```


